apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call not existing
on:
  workflow_dispatch:
jobs:
  call_myself2:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io-2.yaml
