apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call RW with inputs and outputs
on:
  workflow_dispatch:
    inputs:
      p1:
        type: string
        required: false
      p2:
        type: number
        required: false
      p3:
        type: boolean
        required: false
      p4:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: false
jobs:
  call_with_io:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io.yaml
    with:
      mystring: 1
      mynumber: 2
      mybool: 3
      mychoice: 4
