apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call RW with inputs and outputs
on:
  workflow_dispatch:
    inputs:
      mystring:
        type: string
        required: false
      mynumber:
        type: number
        required: false
      mybool:
        type: boolean
        required: false
      mychoice:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: false
jobs:
  call_with_io:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io.yaml
