apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call RW with inputs and outputs
on:
  workflow_dispatch:
    inputs:
      p1:
        type: string
        required: false
      p2:
        type: number
        required: false
      p3:
        type: boolean
        required: false
      p4:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        required: false
jobs:
  call_with_io:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io.yaml
    with:
      mystring: ${{ inputs.p1 }}
      mynumber: ${{ inputs.p2 }}
      mybool: ${{ inputs.p3 }}
      mychoice: ${{ inputs.p4 }}
  use_outputs:
    needs: call_with_io
    steps:
      - name: Print the output of the previous job
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Outpus received: ${{ needs.call_with_io.outputs.output1 }} ${{ needs.call_with_io.outputs.output2 }} "
