apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: indirect loop 1
on:
  workflow_call:
  workflow_dispatch:
jobs:
  call_myself:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/indirect-loop-2.yaml
