apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Loop call myself
on:
  workflow_call:
  workflow_dispatch:
jobs:
  call_myself:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/loop-call-myself.yaml@v1097