apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: name collision
on:
  workflow_dispatch:
jobs:
  outer-1:
    steps:
      - name: outer-1-step
        uses: docker://alpine:3.20
        run: |
          echo "outer-1"
  outer-2:
    needs: outer-1
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/reusable-wf-5.yaml
  outer-2init:
    steps:
      - name: init-step
        uses: docker://alpine:3.20
        run: |
          echo "outer-2-init"
