apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable wf 5
on:
  workflow_call:
    inputs:
      asecret:
        type: string
  workflow_dispatch:
jobs:
  Do_something:
    steps:
      - name: Step 1
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello secret: ${{ inputs.asecret }}"
