apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: rw with io

on:
  workflow_call:
   inputs:
      mystring:
        type: string
        default: lalala
        required: true
      mynumber:
        type: number
        default: 123456
        required: true
      mybool:
        type: boolean
        default: true
        required: true
      mychoice:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt2
        required: true

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Params received: ${{ inputs.mystring }} ${{ inputs.mynumber }} ${{ inputs.mybool }} ${{ inputs.mychoice }} "
