apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: rw with io 2

on:
  workflow_call:
   secrets:
      asecret44:
        description: this is secret 1
        required: true
   outputs:
      out1:
        value: ${{ jobs.build.outputs.output1 }}
        description: Output desc 1
      out2:
        value: ${{ jobs.build.outputs.output2 }}
        description: Output desc 2

jobs:
  build:
    outputs:
      output1: 'this is output1'
      output2: 'this is output2'
    steps:
      - name: Print param and return outputs
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo " this is a secret: ${{ secrets.asecret44 }}"

