apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: rw with io 3

on:
  workflow_call:
   inputs:
      i1:
        type: number
        required: false
      i2:
        type: boolean
        required: false
      i3:
        type: string
        required: false
   secrets:
      s1:
        required: false
      s2:
        required: false
      s3:
        required: false
   outputs:
      out1:
        value: ${{ jobs.build.outputs.output1 }}
      out2:
        value: ${{ jobs.build.outputs.output2 }}
      out3:
        value: ${{ jobs.build.outputs.output3 }}
      out4:
        value: ${{ jobs.build.outputs.output4 }}
      out5:
        value: ${{ jobs.build.outputs.output5 }}
      out6:
        value: ${{ jobs.build.outputs.output6 }}

jobs:
  build:
    outputs:
      output1: "${{ inputs.i1 }}"
      output2: "${{ inputs.i2 }}"
      output3: "${{ inputs.i3 }}"
      output4: "${{ secrets.s1 }}"
      output5: "${{ secrets.s2 }}"
      output6: "${{ secrets.s3 }}"
    steps:
      - name: Print param and return outputs
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo " i1: ${{ inputs.i1 }}"
          echo " i2: ${{ inputs.i2 }}"
          echo " i3: ${{ inputs.i3 }}"
          echo " s1: ${{ secrets.s1 }}"
          echo " s2: ${{ secrets.s2 }}"
          echo " s3: ${{ secrets.s3 }}"


