apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: rw with io

on:
  workflow_call:
   inputs:
      mystring:
        type: string
        # default: lalala
        required: true
      mynumber:
        type: number
        # default: 123456
        required: true
      mybool:
        type: boolean
        # default: true
        required: true
      mychoice:
        type: choice
        options:
          - opt1
          - opt2
          - opt3
        # default: opt2
        required: true
    outputs:
      out1:
        value: ${{ jobs.build.outputs.output1 }}
      out2:
        value: ${{ jobs.scan.outputs.output2 }}

jobs:
  build:
    outputs:
      output1: 'this is output1'
      output2: 'this is output2'
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Params received: ${{ inputs.mystring }} ${{ inputs.mynumber }} ${{ inputs.mybool }} ${{ inputs.mychoice }} "
