apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_call:
metadata:
  stages/v1alpha1:
    - name: inner stage
      jobs:
        - call_rw2
jobs:
  call_rw2:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw2.yaml
