apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Very complex

on:
  workflow_dispatch:
jobs:
  getready:
    steps:
      - name: Print
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "getting ready"
  doit:
    needs: getready
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/very-complex-2.yaml

  