apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call RW with inputs and outputs
on:
  workflow_dispatch:
jobs:
  call_with_io2:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io-2-2.yaml
    secrets:
      asecret44: "hola"
  use_outputs:
    needs: call_with_io2
    steps:
      - name: Print
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Outpus received: ${{ needs.call_with_io2.outputs.out1 }} ${{ needs.call_with_io2.outputs.out2 }} "
  call_with_io2-3:
    uses: mluzcabrera/testreusableworkflows/.cloudbees/workflows/rw-with-io-2-2.yaml
    secrets:
      asecret44: ${{ vars.mlcbProp }}
  use_outputs-3:
    needs: call_with_io2-3
    steps:
      - name: Print
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Outpus received: ${{ needs.call_with_io2-3.outputs.out1 }} ${{ needs.call_with_io2-3.outputs.out2 }} "



